### ISSUE TITLE
Not all collision boxes are exported.

### ISSUE THREAD

**Issue by realModsWanted** [AsoboStudio/glTF-Blender-IO-MSFS#130]
### Current Behavior

I have a small hangar with small sidebuildings, so 3 "buildings" in one object. I've add 3 box colliders for these buildings but only 2 are displayed in MSFS20.
Is the amount of colliders limited to only two per object or is this a bug?

### Expected Behavior

Expect to export all colliders or at least increase the number if limitted.

### Steps To Reproduce

1. Create a cube.
2. Add more than 2 box-colliders.
3. Export and check in MSFS20.

### Environment

```markdown
- OS: Windows 11
- Blender: 3.1.0
- glTF-Blender-IO-MSFS: 1.1.5
```

### Anything else?

![box-collider-missing](https://user-images.githubusercontent.com/98099299/164230311-20e5a8af-6f1f-49f9-a58c-7a206dccd843.jpg)

**Comment by pepperoni505** [comment]
pepperoni505 (at) gmail (dot) com

**Comment by grebwol** [comment]
Same for me. My item needs about 6 of them but I can only export with 2-3 at a time.

**Comment by realModsWanted** [comment]
Hi again.
I did some troubleshooting regarding the problem with the colliders and there is a quite strange behaviour... especially point 7.
I've created an Excel-file to show my tests and to help to recreate. I hope this troubleshooting will help to fix the problem. 


It seems like there are several issues...
1. Collider can't be child of a scene.
2. Collider can't be child of an empty.
3. Collider must be child of an actual 3D object.
4. Collider can't be nested in another collider.
5. Colliders written in the gltf don't work ingame.
6. Colliders NOT written in the gltf do work ingame.
7. Only every second collider gets exported.

![Blender-Exporter-Troubleshooting](https://user-images.githubusercontent.com/98099299/164423534-8bba3872-1446-486d-afe3-52ebbc7deb06.jpg)

**Comment by mamu82** [comment]
> Hi again.
> I did some troubleshooting regarding the problem with the colliders and there is a quite strange behaviour... especially point 7.
> I've created an Excel-file to show my tests and to help to recreate. I hope this troubleshooting will help to fix the problem. 
> 
> 
> It seems like there are several issues...
> 1. Collider can't be child of a Scene-Collection.
> 2. Collider can't be child of an empty.
> 3. Collider must be child of an actual 3D object.
> 4. Collider can't be nested in another collider.
> 5. Colliders written in the gltf don't work ingame.
> 6. Colliders NOT written in the gltf do work ingame.
> 7. Only every second collider will not work ingame but will be entered in the gltf file.
> 
> ![Blender-Exporter-Troubleshooting](https://user-images.githubusercontent.com/98099299/164423534-8bba3872-1446-486d-afe3-52ebbc7deb06.jpg)
> 
> 

Nr 3 Is what Is expected, maybe the docs should be updated because they talk about linking the shape (aka make It child in Blender) 
to a "LOD" <- quite non sense! Should be link to a mesh

But anyways make sense that you are not allowed  a Collider without a shape (no One likes to crash in something invisible, FlyingFabio knows this well 😅)
(I have already gave a look at the python code , there Is a note about this )

[IMG_20220421_130920.jpg](https://user-images.githubusercontent.com/101219759/164446008-71843bf0-5559-4dab-bb5e-2670996b4cc2.jpg)

Nr 6 Is ankward, how can the game know that there is a Collider when not declared in the glTF? 

Nr 7 here Is the real issue, and should be fixed
