### ISSUE TITLE
Problem with DDS textures support

### ISSUE THREAD

**Issue by vpilotdesigns** [AsoboStudio/glTF-Blender-IO-MSFS#151]
### Current Behavior

Cannot import aircraft gltf models with the standard plugin for models with DDS textures with the Official Asobo plugin installed. 
![image](https://user-images.githubusercontent.com/71776971/169887899-e9e22aa0-9c40-4a66-b33e-19a8c86694fc.png)

### Expected Behavior

Import model and not generate an error if it has DDS textures

### Steps To Reproduce

1. File
2. Import
3. GLTF 2.0
4. Choose an MSFS aircraft model
5. Error

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

### Anything else?

The FBW blender addon did work with DDS textures (FBW gltf addon not installed currently)

**Comment by pepperoni505** [comment]
Hi,

The importer in this addon is meant to only import non-compiled .glTF files. You won't be able to import any glTF files that have been built in the sim, which is the case for your file since there's a DDS extension

**Comment by lyonheart001** [comment]
I really liked being able to import Asobo planes (LOD00 models, especially the cabins) as then you could view the node part names, animation names, see how many key frames they needed, and also see how the materials were done, etc.  Life saver.  Glad it still works with FlyByWire version addon.
Being able to import working animation planes with their materials from glTF to Blender was very nice.  

Bill
LHC
    On Monday, May 23, 2022, 01:27:24 PM MST, Jack Lavigne ***@***.***> wrote:  
 
 


Hi,

The importer in this addon is meant to only import non-compiled .glTF files. You won't be able to import any glTF files that have been built in the sim, which is the case for your file since there's a DDS extension

**Comment by pepperoni505** [comment]
> 

The Asobo importer never supported importing built files. This is a common misconception. Asobo do not plan on adding the feature to this tool, for a few internal reasons. If you would like to import built files, FlyByWire is working on an [addon](https://github.com/flybywiresim/msfs-blender-tools) for that, however development has been paused as we don't really have a need for it at this moment.

**Comment by btronquo** [comment]
@vpilotdesigns 
Maybe we can clean the list of the isssues and close this one as you had an answer ?
