### ISSUE TITLE
Blender 3.3 LTS (long term support)

### ISSUE THREAD

**Issue by tonypez** [AsoboStudio/glTF-Blender-IO-MSFS#177]
Hi, 
please update the expoter to blender 3.3 LTS, this version is going to be kept udpated for a long time avoiding the exporter to break at every new blender update.

Everyone should then stick to the LTS version to use the addon.

**Comment by tml1024** [comment]
Hear, hear.

Not holding my breath, though. Last commit on June 14.

**Comment by lyonheart001** [comment]
I have noticed some export issues with models using the MCX-2-glTF format conersion, which saves the animations.  But the new Blender 3.3, 3.4, and 3.5 use a different animation logic or handling, and the animations in 3.3, 3.4, 3.5 are brought in with glTF-2 as being Frame Rates (animation time, frames per second) instead of 'Key Frames' like in the past.  This is with models where animations are saved and were in MDL format for FSX.  This issue wasnt there with Blender 3.2, as it handles these models (in Blender 3.2) without issue (I am using a special remastered version by RonH with subtle teaks to the exporter).  This exports fine.  But 3.3, 3.4, and 3.5 will not export the model and I believe its this animation issue.

Others are not getting this issue, and they are probably not bring in models from MCX (Model Converter X), so they probably have pure animations made in 3.3, 3.4 and 3.5 instead of imported animations.

Hope this helps.  Would be nice to get this fixed, if its possible.  I am in talks with Blender team on this issue, as I think 3.3+ changed in their management of this.  Arno theorizes it could be that Blender 3.3+ now focuses only on glTF-1 format and has issues (in animations) with glTF-2 format.


Bill
Lionheart Creations
