### ISSUE TITLE
Does this work anymore in Blender 3.4?  With any of the Cessna Classic models?

### ISSUE THREAD

**Issue by Kelleytoons** [AsoboStudio/glTF-Blender-IO-MSFS#188]
I've installed this on ALL version of Blender (except for 3.3 - it's only available from the app store and in Windows Apps you can't install this plugin) and I keep getting a "scale" error when trying to import the Classic Cessna model.  This error is well reported all over the web with no real answers, so I just assumed it was impossible, but someone on the MSFS forums says his works just fine.

**Comment by Kelleytoons** [comment]
Here's some video showing how it doesn't work: https://www.youtube.com/watch?v=Sy7uiDp82AQ

**Comment by bestdani** [comment]
Your video reveals that you are trying to use an outdated version of my inofficial quick and dirty importer.

Try to update it and I actually would recommend to use this official importer if it's possible (unfortunately I have no time for some active MSFS subscription to test it myself). Since it is more likely that it gets updates more frequently, supports features not only targeting texture painting and might integrate better into blender.

**Comment by y-khodja** [comment]
Hello, 

The official exporter is getting updated to be used with Blender 3.3.2 LTS. We can't garanty that it would work with all other versions of Blender.

Thank you for your report,
