### ISSUE TITLE
No light when made Import from gltf object 

### ISSUE THREAD

**Issue by Safojas** [AsoboStudio/glTF-Blender-IO-MSFS#299]
### Current Behavior

When i try to import gltf object with light it have no light sources after import. Only empties where lights should be.
<img width="1920" alt="01" src="https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/5460847/4fc174ab-6c4e-48fc-9def-cdc886bed28f">
after import
<img width="1920" alt="02" src="https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/5460847/0cc83f74-6d9a-456a-b586-70421c172d45">

### Expected Behavior

Import should add light sources.

### Steps To Reproduce

Get zip archive and try to import. Open .blend and compare.

### Environment

```markdown
- OS:Windows 10
- Blender:3.3.9
- glTF-Blender-IO-MSFS: 1.3.2
```

### Anything else?

[test.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/13961359/test.zip)

**Comment by ronh991** [comment]
The ASOBO exporter does not do imports.  Function importing may not work as expected. as you have found.

![DA40CGDFQ_2024 01 21_14h30m21s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/78e4d9b4-fd84-4829-a8ed-b8ab19ed7eb7)

**Comment by y-khodja** [comment]
Hello, 

I will look at the problems mentionned about the importer. It should work. 

Thank you for your report

**Comment by y-khodja** [comment]
Hello,

I have looked at this bug, the thing is that the Khronos-exporter/importer imports lights if they have the "KHR_lights_punctual" extension, when we export a model for Microsoft Flight Simulator with the "glTF-Blender-IO-MSFS" we delete this extension because we don't use it in the game. This means that at the import, we don't have it anymore, then the importer does not know that he has lights to create.

**Comment by y-khodja** [comment]
Hello,

I have looked at this bug, the thing is that the Khronos-exporter/importer imports lights if they have the "KHR_lights_punctual" extension, when we export a model for Microsoft Flight Simulator with the "glTF-Blender-IO-MSFS" we delete this extension because we don't use it in the game. This means that at the import, we don't have it anymore, then the importer does not know that he has lights to create. It will then transform it to an empty node.

**Comment by y-khodja** [comment]
Fixed ! 

Thank you for your report
