### ISSUE TITLE
Issue with missing Comp material ( AO/Roughness/Metal ) in MSFS, and normal map in the blender viewport

### ISSUE THREAD

**Issue by BlueMeshs** [AsoboStudio/glTF-Blender-IO-MSFS#76]
### Current Behavior

With the last build V1.1.2 pbr material are not correctly displayed in MSFS (Comp is missing), and normal map is nto correctly rendered in the Blender Viewport.

### Expected Behavior

Have a correct render in MSFS, and it's secondary but better if it's solved, a correct normal map aspect in Blender viewport.

### Steps To Reproduce

- Create a mesh in Blender with a Standard PBR material
- build and export in MSFS

### Environment

```markdown
- OS:Win10
- Blender:3.1.0
- glTF-Blender-IO-MSFS:1.1.2
```

### Anything else?

MSFS Rendered:
![1](https://user-images.githubusercontent.com/96650516/159038671-401ecbce-49f2-4ffc-82ed-dc3c20f1dd5d.JPG)
Albedo Channel:
![2](https://user-images.githubusercontent.com/96650516/159038673-b44e5b54-6930-4ee1-af5b-d99daa378eb8.JPG)
Comp, channel Metallic:
![3](https://user-images.githubusercontent.com/96650516/159038675-b79c2fa0-0d24-41a7-9184-ee0c71be4637.JPG)
Comp, channel Roughness:
![4](https://user-images.githubusercontent.com/96650516/159038676-3f3318f6-05a9-461a-bbc1-3e317fa2140b.JPG)
Comp, channel AO:
![5](https://user-images.githubusercontent.com/96650516/159038679-d1d8db68-a4d9-43fd-9205-24294ece6d8a.JPG)
Normal channel:
![6](https://user-images.githubusercontent.com/96650516/159038680-ffd1dd1c-eecc-44c6-ab14-8dc6db41f54f.JPG)
Blender shading tab: 
![7](https://user-images.githubusercontent.com/96650516/159038682-1d303339-5781-4620-89c7-c5501fc0b862.JPG)
Blender Normal map viewport : 
![8](https://user-images.githubusercontent.com/96650516/159039064-cad8848c-26ce-4fa7-8148-3e8cec71b8f2.JPG)

**Comment by azgoodaz** [comment]
Can confirm. Seems like Metallic/Roughness gets exported properly from Blender to texture folder but it doesn't export upon building the package.

**Comment by Wombii** [comment]
It looks like it's sometimes duplicating the "glTF Settings" in the glTF Settings node when making new materials (see screenshot). When this has a number behind it instead of being set to the original version MSFS will refuse to build the comp texture. Manually selecting the original version fixes this for me.
![image](https://user-images.githubusercontent.com/60835350/159152409-712d4729-821e-4bc4-bfa4-92665896e12f.png)
![image](https://user-images.githubusercontent.com/60835350/159152414-21f48a6e-3a2b-4723-b037-5ac27bacccea.png)

**Comment by pepperoni505** [comment]
#83 and #84 fix this
