### ISSUE TITLE
Spotlights point into the wrong direction

### ISSUE THREAD

**Issue by Mikeaat** [AsoboStudio/glTF-Blender-IO-MSFS#93]
### Current Behavior

if you place a spotlight like this pointing away from the building: 
![image](https://user-images.githubusercontent.com/46610319/159764930-55b23b07-28d8-4c1f-b8be-1a313c16d58f.png)
in the simulator it is 90° rotatet on the blender z axis:
![2022-03-23 18_53_23-Microsoft Flight Simulator - 1 23 12 0](https://user-images.githubusercontent.com/46610319/159765047-a261e5e6-6a68-4891-bacd-b7ec17407e3b.jpg)

### Expected Behavior

the light should point into the same direction like in blender.

### Steps To Reproduce

1. place a spotlamp
2. rotate it on the y axis that it points into a direction
3. export and check in the devmode

### Environment

```markdown
- OS: Win 10
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.3
```

**Comment by myphysicalworld** [comment]
Is there a solution for this issue?

**Comment by btronquo** [comment]
To add some information, I made some tests and here my result: 

Expected (Msfs2blender) : 
```
            "rotation" : [
                0.4999999701976776,
                -0.4999999701976776,
                -0.5,
                0.5
            ],     
```           
                
glTF-Blender-IO-MSFS results: 
```
            "rotation" : [
                0,
                0,
                -0.7071068286895752,
                0.7071068286895752
            ],
```

**Comment by pepperoni505** [comment]
> Is there a solution for this issue?

I will look into this issue this weekend, and will let you know of the solution.

**Comment by myphysicalworld** [comment]
Have you had any luck getting the light rotation values to export to the .glTF?

**Comment by Wombii** [comment]
The exported light needs to be rotated 90 degrees on the x axis. The Blender2MSFS exporter does this in __gather_trans_rot_scale in glt2_blender_gather_nodes.py. 

Possible cause and possible future issue:
I noticed in the gltf this exporter is exporting an extra light orientation node, which led me down a rabbit hole.
The reason it's exporting it wrong is seems to be because the gltf-blender-io exporter changes the nodes to +y up direction instead of +z up when +yup is enabled. Unless it's a light, in which case it's instead adding an extra orientation correction node. MSFS ignores this orientation correction node. (This happens in __gather_node in glt2_blender_gather_nodes.py)

I then found this has recently been changed in the gltf-blender-io so I installed the latest version. In the latest version it's not writing an orientation correction node but instead corrects the light rotation directly.
https://github.com/KhronosGroup/glTF-Blender-IO/issues/1328

With this latest version of gltf-blender-io two things change: 
1: The msfs extended exporter fail to remove the KHR_light_punctual extension (the gltf works after manually removing them).
2: The light is 180 degrees wrong instead of 90.

**Comment by pepperoni505** [comment]
Would someone please mind providing a sample `.blend` file so I can look into this issue properly?

**Comment by Mikeaat** [comment]
@pepperoni505  here you are.
[PunktualLights.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8459831/PunktualLights.zip)

**Comment by Mikeaat** [comment]
@pepperoni505 here you are
[PunktualLights.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8459833/PunktualLights.zip)

**Comment by PhysicsTeacher1** [comment]
Maybe my workaround will help:
1. Set the Transformation Orientation in Blender to GLOBAL (In the center of the top of the 3D window).
2. Set up your spots exactly as you want them in Blender, and check them in Rendered mode.
3. Change the Transformation Orientation to LOCAL. (This is where I was getting lost at first.)
4. With each spot, rotate it 90 degrees positive around the X axis. (R X 90)
5. Verify in the sim.  (Don't forget to set your Transformation Orientation back to GLOBAL.)
I think the difference between setting the angle of the spot in Blender and exporting that same orientation is tied up in the difference between rotation in GLOBAL versus LOCAL axes.  Also, with the Rotation Rate setting, which axis is the "standard" axis around which it should rotate?  (Rhetorical question)

**Comment by lpierabella** [comment]
please test the dedicated PR, so we can approve it

**Comment by Mikeaat** [comment]
> please test the dedicated PR, so we can approve it

tested it with the PR version and it is working correctly!

**Comment by myphysicalworld** [comment]
Tested! Lights came into sim as expected. Thank you.

**Comment by PhysicsTeacher1** [comment]
Answered elsewhere:
Looks like it does exactly as expected. Many, many thanks!
I made sure my addon install was clean, and I first negated all transformations in Blender. That's the first set: Default Angle. Then, to verify correct rotation sense, I set all axes to 45 degrees.
I will be fascinated to see how you did it. I've been mulling over this problem while learning Python; it helps when you're learning something to have a pressing need.
This exporter is thoughtfully designed; I'm never going back
[Test Spotlighting in Asobo Exporter.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8497002/Test.Spotlighting.in.Asobo.Exporter.zip)
.
