### ISSUE TITLE
New GUIDs being generated each time XML is generated and conflicts with GUID in "Scene".xml

### ISSUE THREAD

**Issue by myphysicalworld** [AsoboStudio/glTF-Blender-IO-MSFS#97]
### Current Behavior

Every time "Generate XML" is ran a brand new GUID is generated which is different from the GUID written to the "scene".xml. This cause your up dated object to be "Unknown" in the simulator. One would have to go into the .gltf file and copy the new GUID and paste it into the "LibraryObject name=" location for the updated object. A work around has been to only create the XML the first time you add an object to your scenery and then uncheck "Generate XML" for subsequent updates. However, the Blender2MSFS2 would do a check to see if the object already has a GUID, and if it does it would not generate a GUID. This saved a lot of time as you did not have to check the xmls for matching GUIDs.

### Expected Behavior

Exporter needs to check to see if a GUID has been generated already and if so, do not generate a new GUID.....use the previous one.

### Steps To Reproduce

1. make a new object in Blender
2. Export with Generate XML checked
3. Build Package
4. In Sim, add new object
5. Build Package
6. Go into Blender and make a change to object
7. Export with Generate XML checked
8. open .gltf and "scene".xml in Notepad++ and compare GUIDs, they will be different and in the sim, you will have an object named "Unknown"

### Environment

```markdown
- OS: windows 10 pro
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.3
```

**Comment by Pyscen312** [comment]
I suggest this be optional.  Optional as in creating a new GUID or not. Let the developer decide.

**Comment by Mikeaat** [comment]
just for a little bit more infos the "old" exporter did a check if there is a .xml file in the output directory and reused the GUID if so.:
https://github.com/tml1024/Blender2MSFS2/blob/main/exporter/exp/msfs_xml_export.py
![image](https://user-images.githubusercontent.com/46610319/159976993-3a07676f-a888-46f7-9d27-b30433ccac76.png)

**Comment by realModsWanted** [comment]
Yes, the logic in the "old" exporter was, that it checked for the xml and GUID, if there was one, he used it. If not, a new GUID was generated.

Maybe an "overwrite GUID" option would be possible. If the exporter recognizes, that there is a GUID, then overwrite the GUID if option ticked, if not ticked use the existing one, else create a new one.

**Comment by btronquo** [comment]
I was about to ask _"What would be the case where an user need to overwrite the GUID  ?"_
but indeed, we could have a case where there is a duplicated guid somewhere (even if there is 0.0001% chances) and therefore,we would need to create a new GUID. 

IMO, it could be a checkbox, unchecked by default with the label "Generate New GUID"

**Comment by realModsWanted** [comment]
Maybe I am wrong and haven't understood the working principles of GUID and object assignments. So please correct me, if I'm wrong. I think the biggest problem we are facing now is the following. 

Many Devs have been exporting with the "old" exporter by Vitus. So there are many objects whith generated XML files and GUIDs which are already in the scenery in MSFS.
The problem now is, that when we export an old model (if we make some updates on a building for example) with the new exporter, a new XML and GUID is generated (instead of keeping the old GUID) for this gltf. Afterwards, when we build the package to get our model into the sim, the building which is already in the scene disappears and shows as "unknown" in the scenery editor in MSFS instead of getting updated. And somehow does the "replace" function not always work (but I think this is an MSFS issue and not the exporter issue). So you have to delete the "unknown" building and add it again and position/rotate it to the old position... which can be tidius if you have many objects to update.

So at the moment as workaround I don't let the exporter create an XML/GUID, but just to export the objects, when I update an existing building. And after building the package the building gets updated in the SIM insted of disappearing and showing "unknown" in the scenery editor.

**Comment by pepperoni505** [comment]
Fixed in #100

**Comment by lpierabella** [comment]
this should be ok now...can I close the issue? @myphysicalworld

**Comment by myphysicalworld** [comment]
Yes you can. Thank you very much.
